/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopProductsRouteImport } from './routes/shop.products'
import { Route as ShopCheckoutRouteImport } from './routes/shop.checkout'
import { Route as ShopCartRouteImport } from './routes/shop.cart'
import { Route as ShopProductSlugRouteImport } from './routes/shop.product.$slug'
import { Route as ShopCheckoutSuccessRouteImport } from './routes/shop.checkout.success'

const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductsRoute = ShopProductsRouteImport.update({
  id: '/shop/products',
  path: '/shop/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/shop/checkout',
  path: '/shop/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/shop/cart',
  path: '/shop/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductSlugRoute = ShopProductSlugRouteImport.update({
  id: '/shop/product/$slug',
  path: '/shop/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCheckoutSuccessRoute = ShopCheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ShopCheckoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wholesale': typeof WholesaleRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRouteWithChildren
  '/shop/products': typeof ShopProductsRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/checkout/success': typeof ShopCheckoutSuccessRoute
  '/shop/product/$slug': typeof ShopProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wholesale': typeof WholesaleRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRouteWithChildren
  '/shop/products': typeof ShopProductsRoute
  '/shop': typeof ShopIndexRoute
  '/shop/checkout/success': typeof ShopCheckoutSuccessRoute
  '/shop/product/$slug': typeof ShopProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wholesale': typeof WholesaleRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRouteWithChildren
  '/shop/products': typeof ShopProductsRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/checkout/success': typeof ShopCheckoutSuccessRoute
  '/shop/product/$slug': typeof ShopProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/products'
    | '/sitemap.xml'
    | '/wholesale'
    | '/shop/cart'
    | '/shop/checkout'
    | '/shop/products'
    | '/shop/'
    | '/shop/checkout/success'
    | '/shop/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/products'
    | '/sitemap.xml'
    | '/wholesale'
    | '/shop/cart'
    | '/shop/checkout'
    | '/shop/products'
    | '/shop'
    | '/shop/checkout/success'
    | '/shop/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/products'
    | '/sitemap.xml'
    | '/wholesale'
    | '/shop/cart'
    | '/shop/checkout'
    | '/shop/products'
    | '/shop/'
    | '/shop/checkout/success'
    | '/shop/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ProductsRoute: typeof ProductsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WholesaleRoute: typeof WholesaleRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopCheckoutRoute: typeof ShopCheckoutRouteWithChildren
  ShopProductsRoute: typeof ShopProductsRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopProductSlugRoute: typeof ShopProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/products': {
      id: '/shop/products'
      path: '/shop/products'
      fullPath: '/shop/products'
      preLoaderRoute: typeof ShopProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout': {
      id: '/shop/checkout'
      path: '/shop/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/shop/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/product/$slug': {
      id: '/shop/product/$slug'
      path: '/shop/product/$slug'
      fullPath: '/shop/product/$slug'
      preLoaderRoute: typeof ShopProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout/success': {
      id: '/shop/checkout/success'
      path: '/success'
      fullPath: '/shop/checkout/success'
      preLoaderRoute: typeof ShopCheckoutSuccessRouteImport
      parentRoute: typeof ShopCheckoutRoute
    }
  }
}

interface ShopCheckoutRouteChildren {
  ShopCheckoutSuccessRoute: typeof ShopCheckoutSuccessRoute
}

const ShopCheckoutRouteChildren: ShopCheckoutRouteChildren = {
  ShopCheckoutSuccessRoute: ShopCheckoutSuccessRoute,
}

const ShopCheckoutRouteWithChildren = ShopCheckoutRoute._addFileChildren(
  ShopCheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ProductsRoute: ProductsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WholesaleRoute: WholesaleRoute,
  ShopCartRoute: ShopCartRoute,
  ShopCheckoutRoute: ShopCheckoutRouteWithChildren,
  ShopProductsRoute: ShopProductsRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopProductSlugRoute: ShopProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
